services:
  - type: web
    name: telegram-bot
    env: node
    plan: free
    buildCommand: npm ci && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: NODE_OPTIONS
        value: '--max-old-space-size=460'
    healthCheckPath: /
